#!/bin/sh -e

if [ ! -h src/github.com/coreos/nova-agent-watcher ]; then
	mkdir -p src/github.com/coreos/
	ln -s ../../.. src/github.com/coreos/nova-agent-watcher
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}

go build -o bin/nova-agent-watcher github.com/coreos/nova-agent-watcher
