#!/bin/bash -e

export GOPATH=${PWD}/Godeps/_workspace
export GOBIN=${PWD}/bin

if [ ! -h $GOPATH/src/github.com/coreos/nova-agent-watcher ]; then
    mkdir -p $GOPATH/src/github.com/coreos/
    ln -s ../../../../../ $GOPATH/src/github.com/coreos/nova-agent-watcher
fi

eval $(go env)

go install github.com/coreos/nova-agent-watcher
